project_id = "vepiybjuqvvpeyxaycst"

[functions.create-checkout]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.track-purchase]
verify_jwt = false
